soctherm: fix compile error when DEBUG_FS=n
fix below -Werror=unused-function error when CONFIG_DEBUG_FS=n:

tegra_soctherm.c:634:12: error: 'temp_translate_reverse'
defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors
make[5]: *** [drivers/platform/tegra/tegra_soctherm.o] Error 1
make[5]: *** Waiting for unfinished jobs....

Bug 1778001
Bug 200318280

Change-Id: Icc1bcdcea22e633d8f527c484b818251f688360b
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1206146
(cherry picked from commit c956655e11beed7d7b6341ac6f9658b27f0f1454)
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503156
GVS: Gerrit_Virtual_Submit
Reviewed-by: Vinayak Pane <vpane@nvidia.com>