ARM: Tegra: fix compile error when DEBUG_FS is off
there is compile error as below when CONFIG_DEBUG_FS=n:
fix it by using correct function prototype of tegra_edp_debugfs_init.

cpu-edp.c: In function 'tegra_cpu_edp_probe':
cpu-edp.c:343:2: error: too many arguments to function
'tegra_edp_debugfs_init'
cpu-edp.c:241:19: note: declared here
make[5]: *** [drivers/platform/tegra/cpu-edp.o] Error 1

gpu-edp.c: In function 'tegra_gpu_edp_probe':
gpu-edp.c:313:2: error: too many arguments to function 'tegra_edp_debugfs_init'
gpu-edp.c:194:19: note: declared here
make[5]: *** [drivers/platform/tegra/gpu-edp.o] Error 1

Bug 1778001
Bug 200318280

Change-Id: I45c74947a37603d82c38dec7e2492ff25f36d065
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1206139
(cherry picked from commit 1b317ad87355e53bffd87189b52d790286a97ec0)
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503154
GVS: Gerrit_Virtual_Submit
Reviewed-by: Vinayak Pane <vpane@nvidia.com>