platfotrm: tegra: fix build error when DEBUG_FS=n
fix below build errors when CONFIG_DEBUG_FS is not set:

kernel/kernel-3.10/drivers/platform/tegra/cpu-tegra.c:69:21:
error: ‘force_cpupwr’ defined but not used [-Werror=unused-variable]
 static unsigned int force_cpupwr;
                     ^
kernel/kernel-3.10/drivers/platform/tegra/cpu-tegra.c:70:21:
error: ‘force_cpupwr_freqcap’ defined but not used [-Werror=unused-variable]
 static unsigned int force_cpupwr_freqcap;
                     ^
cc1: all warnings being treated as errors

Bug 1778001
Bug 200237545

Change-Id: I80673f6bf60529fc08d3a6adaf8e1ddcdfda2bc0
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1211555
(cherry picked from commit a31b31e29b693f087841796bcfb40051abbf39ab)
Signed-off-by: Nitin Kumbhar <nkumbhar@nvidia.com>
Reviewed-on: http://git-master/r/1276027
(cherry picked from commit c5010099414471c134cf8a59d504808f5dbbc221)
Reviewed-on: https://git-master.nvidia.com/r/1528626
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>
Reviewed-by: Daniel Fu <danifu@nvidia.com>