video:tegra:nvmap: fix compile error if DEBUG_FS=n
there is compile error when CONFIG_DEBUG_FS=n,
fix it by adding dummy nvmap_heap_debugfs_init function if
CONFIG_DEBUG_FS is notdefined.

nvmap_heap.c: In function 'nvmap_heap_debugfs_init':
nvmap_heap.c:94:3: error: implicit declaration of function
'debugfs_create_x64' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[6]: *** [drivers/video/tegra/nvmap/nvmap_heap.o] Error 1
make[5]: *** [drivers/video/tegra/nvmap] Error 2

Bug 1778001
Bug 200318280

Change-Id: I331988b7c7ccc1f5dff9381de6e1ca0f422905f0
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1206134
(cherry picked from commit 094cb7fa00b59b451a08e041f6dbeca4a971a6c1)
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503160
GVS: Gerrit_Virtual_Submit
Reviewed-by: Vinayak Pane <vpane@nvidia.com>