ARM: tegra: dvfs: fix comile error when DEBUG_FS=n
Fix below [-Werror=unused-function] error when CONFIG_DEBUG_FS =n
and CONFIG_TEGRA_VDD_CORE_OVERRIDE = n.

dvfs.c:1466:12: error: 'dvfs_rail_get_override_floor' defined
but not used [-Werror=unused-function]
static int dvfs_rail_get_override_floor(struct dvfs_rail *rail)

cc1: all warnings being treated as errors
make[6]: *** [drivers/platform/tegra/dvfs.o] Error 1
make[5]: *** [drivers/platform/tegra] Error 2

Bug 200318280

Change-Id: I67220b42360dd956ff42973d99f2a0cfb18888f8
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503153
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Aleksandr Frid <afrid@nvidia.com>
Reviewed-by: Vinayak Pane <vpane@nvidia.com>