arm64: dma-mapping: fix build error when DEBUG_FS=n
Fix build errors when CONFIG_DEBUG_FS=n:

dma-mapping.c: In function 'dma_debugfs_platform_info':
dma-mapping.c:1085:9: error: 'dump_iommu_mappings_fops'
undeclared (first use in this function)

Bug 200237545

Change-Id: Icdcd80c79046ec66889d1f045291a389c9deb40b
Signed-off-by: Nitin Kumbhar <nkumbhar@nvidia.com>
Reviewed-on: http://git-master/r/1286013
(cherry picked from commit a84b835b1b605a48a81ccbfa1a7f0886a3da3ef1)
Reviewed-on: https://git-master.nvidia.com/r/1528621
GVS: Gerrit_Virtual_Submit
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>
Reviewed-by: Daniel Fu <danifu@nvidia.com>