arm64: tegra: fix build error when DEBUG_FS=n
fix below build errors when CONFIG_DEBUG_FS is not set:

denver-knobs.c:123:24: error: ‘nvg_lock’ defined but not used
[-Werror=unused-variable]
 static DEFINE_SPINLOCK(nvg_lock);

arch/arm64/mach-tegra/built-in.o: In function `hardwood_init':
kernel/kernel-3.10/arch/arm64/mach-tegra/denver-hardwood.c:743:
undefined reference to `denver_backdoor_enabled'
make[2]: *** [vmlinux] Error 1
make[1]: *** [sub-make] Error 2
^

Bug 1778001
Bug 200237545

Change-Id: I1bf48c8bdc3bb68c7ac512bec4aca1ae54cb2eae
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1211508
(cherry picked from commit 158c8e31393b3b0052272be5a3f0faa659141fd9)
Signed-off-by: Nitin Kumbhar <nkumbhar@nvidia.com>
Reviewed-on: http://git-master/r/1276030
(cherry picked from commit 66071fd34064090c84dd595ad43609a3114a6f03)
Reviewed-on: https://git-master.nvidia.com/r/1528622
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>
Reviewed-by: Daniel Fu <danifu@nvidia.com>