nvadsp: fix compile error when DEBUG_FS=n
fix below -Werror=undef error when CONFIG_DEBUG_FS=n:

In file included from dev.c:37:0:
dev.h:111:5: error: "CONFIG_DEBUG_FS" is not defined [-Werror=undef]
 #if CONFIG_DEBUG_FS
     ^
dev.c: In function 'nvadsp_probe':
dev.c:461:5: error: "CONFIG_DEBUG_FS" is not defined [-Werror=undef]
 #if CONFIG_DEBUG_FS
     ^
cc1: all warnings being treated as errors
make[6]: *** [drivers/platform/tegra/nvadsp/dev.o] Error 1
make[5]: *** [drivers/platform/tegra/nvadsp] Error 2

Bug 1778001
Bug 200237545
Bug 200318280

Change-Id: I76b43be85d4306d1a20e354e5e95db5a915aef2a
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1210491
(cherry picked from commit 171d4a7f4c5e3692fcea201e9b9cb5d528c8a67d)
Signed-off-by: Nitin Kumbhar <nkumbhar@nvidia.com>
Reviewed-on: http://git-master/r/1276018
(cherry picked from commit 104e74839cd9ce3d4d7f0fde47fda96b24a454c6)
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503151
GVS: Gerrit_Virtual_Submit
Reviewed-by: Vinayak Pane <vpane@nvidia.com>