video:tegra:hdmi:fix compile error when DEBUG_FS=n
tegra_hdmi_set/get_hotplug_state are defined for CONFIG_DEBUG_FS=y only, it
causes below compile error with CONFIG_DEBUG_FS=n,
fix it by moving it out from 'ifdef CONFIG_DEBUG_FS' section.

drivers/built-in.o: In function `nvhdcp_fallback_worker':
hdmihdcp.c:1253: undefined reference to `tegra_hdmi_get_hotplug_state'
hdmihdcp.c:1260: undefined reference to `tegra_hdmi_set_hotplug_state'
hdmihdcp.c:1269: undefined reference to `tegra_hdmi_set_hotplug_state'
make[2]: *** [vmlinux] Error 1
make[1]: *** [sub-make] Error 2

also fix minor checkpatch error by adding comment for rmb().

Bug 1778001
Bug 200318280

Change-Id: If6b803d4366f3e6358c30bcf1e1a87aa1578e716
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1213086
(cherry picked from commit 39e02ec4f0cb559bf4bfc176c1ad02195afc320b)
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503161
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Vinayak Pane <vpane@nvidia.com>