gpu: nvgpu: fix build error with DEBUG_FS=n
Fix build issues seen with CONFIG_DEBUG_FS disabled. Following
issues are fixed with this patch.

gk20a.c: In function 'gk20a_init_gpu_characteristics':
gk20a.c:2032:11: error: 'struct mm_gk20a' has no member named 'disable_bigpage'

gr_gk20a.c: In function 'gr_gk20a_debugfs_init':
gr_gk20a.c:7367:3: error: 'struct gk20a' has no member named 'debugfs_gr_default_attrib_cb_size'

pmu_gk20a.c:4279:5: error: "CONFIG_DEBUG_FS" is not defined [-Werror=undef]

Bug 200237545

Change-Id: I06a984874fbfd7ac86e9fd9d48a6b0faedb715e2
Signed-off-by: Nitin Kumbhar <nkumbhar@nvidia.com>
Reviewed-on: http://git-master/r/1276034
(cherry picked from commit 69c4ecda06aab919e0648bbba9dc0a3d4b91a4bb)
Reviewed-on: https://git-master.nvidia.com/r/1528624
GVS: Gerrit_Virtual_Submit
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>
Reviewed-by: Daniel Fu <danifu@nvidia.com>