video: tegra: dc:fix compile error when DEBUG_FS=n
fix below compile error with CONFIG_DEBUG_FS=n:

dc.c:603:13: error: '_dump_regs' defined but not used
[-Werror=unused-function]
cc1: all warnings being treated as errors
make[6]: *** [drivers/video/tegra/dc/dc.o] Error 1

nvsr.c:51:13: error: 'tegra_dc_nvsr_get' defined but not used
[-Werror=unused-function]
nvsr.c:57:13: error: 'tegra_dc_nvsr_put' defined but not used
[-Werror=unused-function]
cc1: all warnings being treated as errors
make[6]: *** [drivers/video/tegra/dc/nvsr.o] Error 1

Bug 1778001
Bug 200318280

Change-Id: I68ed5c771404e2f4a2894cfd02767989ad7cbb0a
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1206148
(cherry picked from commit 5812b6440598b8814b340dc6754e2e48fe48e15b)
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503158
GVS: Gerrit_Virtual_Submit
Reviewed-by: Vinayak Pane <vpane@nvidia.com>