arm64:dma-mapping: fix build error when DEBUG_FS=n
fix build errors when CONFIG_DEBUG_FS=n:
1) only use dump_iommu_mappings_fops with CONFIG_DEBUG_FS defined.
2) only use __tracepoint_dmadebug_unmap_page when CONFIG_FTRACE is
   defined(CONFIG_FTRACE selects CONFIG_DEBUG_FS, so to disable CONFIG_DEBUG_FS,
   CONFIG_FTRACE will be disabled at first).

dma-mapping.c: In function 'dma_debugfs_platform_info':
dma-mapping.c:1134:9: error: 'dump_iommu_mappings_fops' undeclared (first use
		in this function)
        &dump_iommu_mappings_fops);
         ^
dma-mapping.c:1134:9: note: each undeclared identifier is reported only once
for each function it appears in
dma-mapping.c: In function 'arm_coherent_iommu_unmap_page':
dma-mapping.c:2193:24: error: '__tracepoint_dmadebug_unmap_page' undeclared (
		first use in this function)
  if (static_key_false(&__tracepoint_dmadebug_unmap_page.key))
                        ^
  CC      arch/arm64/mm/init.o
make[3]: *** [arch/arm64/mm/dma-mapping.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      fs/open.o
  CC      fs/read_write.o
make[2]: *** [arch/arm64/mm] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC      fs/file_table.o

dma-mapping.c: In function 'arm_coherent_iommu_unmap_page':
dma-mapping.c:2192:24: error: '__tracepoint_dmadebug_unmap_page' undeclared (
		first use in this function)
  if (static_key_false(&__tracepoint_dmadebug_unmap_page.key))
                        ^
dma-mapping.c:2192:24: note: each undeclared identifier is reported only once
for each function it appears in
make[3]: *** [arch/arm64/mm/dma-mapping.o] Error 1
make[2]: *** [arch/arm64/mm] Error 2
make[2]: *** Waiting for unfinished jobs....

Bug 1778001
Bug 200318280

Change-Id: I27c8d8d153f263ed028fa216db847dad9e24cc42
Signed-off-by: David Pu <dpu@nvidia.com>
Reviewed-on: http://git-master/r/1210477
(cherry picked from commit b4f2a4d829b76a72faf0266b28e019fc91522700)
Signed-off-by: Daniel Fu <danifu@nvidia.com>
Reviewed-on: http://git-master/r/1503147
GVS: Gerrit_Virtual_Submit
Reviewed-by: Vinayak Pane <vpane@nvidia.com>